name: Release Mod
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Mod
        run: |
          MOD_NAME=$(jq -r .name info.json)
          MOD_VERSION=$(jq -r .version info.json)
          ZIP_NAME="${MOD_NAME}_${MOD_VERSION}.zip"
          zip -r "$ZIP_NAME" . -x ".git*" ".github/*"
          echo "MOD_NAME=$MOD_NAME" >> $GITHUB_ENV
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload to Factorio Mod Portal (init)
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.FACTORIO_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"mod": "${{ env.MOD_NAME }}" }' \
            "https://mods.factorio.com/api/v2/mods/releases/init_upload")
          echo $RESPONSE
          echo "UPLOAD_URL=$(echo $RESPONSE | jq -r .upload_url)" >> $GITHUB_ENV

      - name: Upload to Factorio Mod Portal (finish)
        run: |
          ZIP_NAME="${{ env.ZIP_NAME }}"
          UPLOAD_URL="${{ env.UPLOAD_URL }}"
          echo "Uploading $ZIP_NAME to $UPLOAD_URL ..."
          curl -X POST "$UPLOAD_URL" \
            -H "Authorization: Bearer ${{ secrets.FACTORIO_API_KEY }}" \
            -F "file=@${ZIP_NAME}" \
            -o upload_result.json
          cat upload_result.json

      # 上传到 GitHub Release
      # - name: Upload to GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: ${{ env.ZIP_NAME }}
      #     body: |
      #       🚀 自动发布 Factorio Mod
      #       - Mod: **${{ env.MOD_NAME }}**
      #       - Version: **${{ env.MOD_VERSION }}**
      #       - Tag: **${{ github.ref_name }}**
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
