name: Release Mod
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip Mod
        run: |
          MOD_NAME=$(jq -r .name info.json)
          MOD_VERSION="${GITHUB_REF_NAME#v}"
          echo ${MOD_VERSION}
          ZIP_NAME="${MOD_NAME}_${MOD_VERSION}.zip"
          DirName="$(basename `pwd`)"
          jq --arg v "$MOD_VERSION" '.version = $v' info.json > info_tmp.json && mv info_tmp.json info.json
          cd .. && zip -q -r $ZIP_NAME $DirName/*
          echo "MOD_NAME=$MOD_NAME" >> $GITHUB_ENV
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
          echo "ZIP_NAME=`pwd`/$ZIP_NAME" >> $GITHUB_ENV
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
          body: |
            - Mod: **${{ env.MOD_NAME }}**
            - Version: **${{ env.MOD_VERSION }}**
            - Tag: **${{ github.ref_name }}**
      - name: Upload to Factorio Mod Portal (init)
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.FACTORIO_API_KEY }}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d 'mod=${{ env.MOD_NAME }}' \
            "https://mods.factorio.com/api/v2/mods/releases/init_upload")
          echo $RESPONSE
          echo "UPLOAD_URL=$(echo $RESPONSE | jq -r .upload_url)" >> $GITHUB_ENV
      - name: Upload to Factorio Mod Portal (finish)
        run: |
          ZIP_NAME="${{ env.ZIP_NAME }}"
          UPLOAD_URL="${{ env.UPLOAD_URL }}"
          echo "Uploading $ZIP_NAME to $UPLOAD_URL ..."
          curl -X POST "$UPLOAD_URL" \
            -H "Authorization: Bearer ${{ secrets.FACTORIO_API_KEY }}" \
            -F "file=@${ZIP_NAME}" \
            -o upload_result.json
          success=$(cat upload_result.json | jq -r '.success')
